
##BIENVENIDO AL YML DE DECLARACION DE ACCIONES DE AZ PIPELINES
trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: LAYER
  value: 'shared-services'
- name: ENVIRONMENT
  value: 'dev'
- name: STR_ACT
  value: 'stsharedsvcdev100eu2'
- name: RSC_GROUP_BACKEND
  value: 'RG-SHAREDSVC-DEV-100-EU2-ARQSOP'
- name: SERVICE_ACCOUNT
  value: 'sp-arqsop-sharedservices-dev-001-devops'
- name: SUBSCRIPTION_ID
  value: 'd32248ab-7cca-4946-9991-f94c7ba40ebd'
- name: RSC_GROUP
  value: 'RG-SHARED-DEV-001-EU2-ARQSOP'

stages:
- stage: PLAN_STAGE_${{ variables.ENVIRONMENT }}
  displayName: PLAN_STAGE_${{ variables.ENVIRONMENT }}
  jobs:
    - deployment: APROBACION_INICIO_${{ variables.ENVIRONMENT }}
      environment: PIPELINE-MANAGER
    - job: PLAN_STAGE_${{ variables.ENVIRONMENT }}
      continueOnError: false
      dependsOn: APROBACION_INICIO_${{ variables.ENVIRONMENT }}
      steps:
      - checkout: self
      - checkout: git://PLATAFORMA-DE-SOPORTE-CC/IAAC-MODULES-REPOSITORY@main-fase2
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        inputs:
          terraformVersion: '0.14.10'
      - task: TerraformTaskV1@0
        displayName: INIT
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          backendServiceArm: '${{ variables.SERVICE_ACCOUNT }}'
          backendAzureRmResourceGroupName: '${{ variables.RSC_GROUP_BACKEND }}'
          backendAzureRmStorageAccountName: '${{ variables.STR_ACT }}'
          backendAzureRmContainerName: '${{ variables.LAYER }}-${{ variables.ENVIRONMENT }}'
          backendAzureRmKey: 'terraform_base.tfstate'
      - task: TerraformTaskV1@0
        displayName: VALIDATE
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
      - task: TerraformTaskV1@0
        displayName: PLAN
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          environmentServiceNameAzureRM: '${{ variables.SERVICE_ACCOUNT }}'
          #- task: TerraformCLI@0
      - task: Bash@0
        displayName: state
        inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
            backendServiceArm: '${{ variables.SERVICE_ACCOUNT }}'
            backendAzureRmResourceGroupName: '${{ variables.RSC_GROUP_BACKEND }}'
            backendAzureRmStorageAccountName: '${{ variables.STR_ACT }}'
            backendAzureRmContainerName: '${{ variables.LAYER }}-${{ variables.ENVIRONMENT }}'
            backendAzureRmKey: 'terraform_base.tfstate'
            backendAzureRmSubscriptionId: '${{ variables.SUBSCRIPTION_ID }}'
            script: |
                FILE=terraform_test.tfstate; if [ -f "$FILE" ]; then; terraform state list ; fi


- stage: APPLY_STAGE_${{ variables.ENVIRONMENT }}
  dependsOn: PLAN_STAGE_${{ variables.ENVIRONMENT }}
  displayName: APPLY_STAGE_${{ variables.ENVIRONMENT }}
  jobs:
    - deployment: APROBACION_APPLY_${{ variables.ENVIRONMENT }}
      environment: TF-ACTIONS
    - job: APPLY_STAGE_${{ variables.ENVIRONMENT }}
      timeoutInMinutes: 480
      continueOnError: false
      dependsOn: APROBACION_APPLY_${{ variables.ENVIRONMENT }}
      steps:
      - checkout: self
      - checkout: git://PLATAFORMA-DE-SOPORTE-CC/IAAC-MODULES-REPOSITORY@main-fase2
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        inputs:
          terraformVersion: '0.14.10'
      - task: TerraformTaskV1@0
        displayName: INIT
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          backendServiceArm: '${{ variables.SERVICE_ACCOUNT }}'
          backendAzureRmResourceGroupName: '${{ variables.RSC_GROUP_BACKEND }}'
          backendAzureRmStorageAccountName: '${{ variables.STR_ACT }}'
          backendAzureRmContainerName: '${{ variables.LAYER }}-${{ variables.ENVIRONMENT }}'
          backendAzureRmKey: 'terraform_base.tfstate'
      - task: TerraformTaskV1@0
        displayName: APPLY
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          environmentServiceNameAzureRM: '${{ variables.SERVICE_ACCOUNT }}'

#- stage: SECURITY_VERIFICATION_STAGE_${{ variables.ENVIRONMENT }}
#  dependsOn: APPLY_STAGE_${{ variables.ENVIRONMENT }}
#  displayName: SECURITY_STAGE_${{ variables.ENVIRONMENT }}
#  pool:
#    vmImage: 'windows-2019'
#  jobs:
#    - job: SECURITY_VERIFICATION_STAGE_${{ variables.ENVIRONMENT }}
#      continueOnError: true
#      steps:
#      - task: AzSKSVTs@4
#        inputs:
#          ConnectedServiceNameARM: '${{ variables.SERVICE_ACCOUNT }}'
#          GenerateMethodParameterSetSelection: 'ResourceGroupName'
#          ResourceGroupName: '${{ variables.RSC_GROUP }}'
#          SubscriptionId: '${{ variables.SUBSCRIPTION_ID }}'
#          EnableOMSLogging: false
#          AggregateControlsStatus: false

- stage: DESTROY_STAGE_${{ variables.ENVIRONMENT }}
#  dependsOn: SECURITY_VERIFICATION_STAGE_${{ variables.ENVIRONMENT }}
  displayName: DESTROY_STAGE_${{ variables.ENVIRONMENT }}
  jobs:
    - deployment: APROBACION_DESTROY_${{ variables.ENVIRONMENT }}
      environment: TF-ACTIONS
    - job: DESTROY_STAGE_${{ variables.ENVIRONMENT }}
      continueOnError: false
      dependsOn: APROBACION_DESTROY_${{ variables.ENVIRONMENT }}
      steps:
      - checkout: self
      - checkout: git://PLATAFORMA-DE-SOPORTE-CC/IAAC-MODULES-REPOSITORY@main-fase2
      - task: TerraformTaskV1@0
        displayName: INIT
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          backendServiceArm: '${{ variables.SERVICE_ACCOUNT }}'
          backendAzureRmResourceGroupName: '${{ variables.RSC_GROUP_BACKEND }}'
          backendAzureRmStorageAccountName: '${{ variables.STR_ACT }}'
          backendAzureRmContainerName: '${{ variables.LAYER }}-${{ variables.ENVIRONMENT }}'
          backendAzureRmKey: 'terraform_base.tfstate'
      - task: TerraformTaskV1@0
        displayName: DESTROY
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/'
          environmentServiceNameAzureRM: '${{ variables.SERVICE_ACCOUNT }}'
