name: "$(Rev:rr)"

# Trigger only on master/main branch and pull requests to master/main
trigger:
  branches:
    include:
      - master
      - main
      - devops-test

pr:
  branches:
    include:
      - master
      - main

pool:
  vmImage: "ubuntu-22.04"

variables:
  - template: ../variables/variables.yaml

stages:
- stage: Security
  jobs:
  - job: configuration
    steps:
    - checkout: self
      clean: "true"
    - script: |
        docker run --tty --rm -v "$PWD:/app" -w /app bridgecrew/checkov --directory /app
- stage: Validation
  jobs:
  - job: b
- stage: Terraform
  jobs:
  - job: init
  - job: plan
  - job: apply

