name: "$(Rev:rr)"

# Trigger only on master/main branch and pull requests to master/main
trigger:
  branches:
    include:
      - master
      - main
      - devops-test

pr:
  branches:
    include:
      - master
      - main

pool:
  vmImage: "ubuntu-22.04"

variables:
  - template: ../variables/variables.yaml

stages:
- stage: Security
  jobs:
  - job: configuration
    steps:
    - checkout: self
      clean: "true"
    - script: docker run --tty --rm -v "$PWD/infra:/app" -w /app bridgecrew/checkov --directory /app
      displayName: Checkov
- stage: Validation
  jobs:
  - job: Lint
    steps: 
    - checkout: self
      clean: "true"
    - script: docker run --rm -v "$PWD/infra:/app" -w /app  hashicorp/terraform init
      displayName: Terraform init
    - script: docker run --rm -v "$PWD/infra:/app" -w /app  hashicorp/terraform validate
      displayName: Terraform validate
    - script: docker run --rm -v "$PWD/infra:/app" -w /app  hashicorp/terraform fmt -recursive
      displayName: Terraform fmt
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/infra
        artifact: infra-$(Build.BuildNumber)
        publishLocation: pipeline

- stage: Plan
  jobs:
  - job: plan
    - steps:
      download: current
      artifact: infra-$(Build.BuildNumber)
    - script: docker run --rm -v "$PWD/infra-$(Build.BuildNumber):/app" -w /app  hashicorp/terraform plan
      displayName: Terraform plan
